sudo: required
language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

before_script:
  - |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
      export PATH=$HOME/.cargo/bin:$PATH &&
      cargo install cargo-update || echo "cargo-update already installed" &&
      cargo install cargo-travis || echo "cargo-travis already installed" &&
      cargo install-update -a
  fi

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo bench
  - cargo run ashpaper-bin/poems/lovely-poem.eso

after_success:
  -|
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo coveralls
  fi
