sudo: required
language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - if [ ! -f $HOME/.cargo/bin/cargo-coveralls ]; then
      cargo install cargo-travis;
    fi

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo run ashpaper-bin/poems/lovely-poem.eso

after_success:
  - cargo coveralls
